### PR TITLE
fix: Add text truncation in ONNX encoding.

### PR DESCRIPTION
**Pull request by wxywb**

### CODE REVIEW

**Comment by wxywb** [comment]
https://github.com/milvus-io/milvus-model/issues/57

**Comment by codingjaguar** [comment]
Update documentation or example to reflect this new feature?

**Comment by wxywb** [comment]
> Update documentation or example to reflect this new feature?

This feature is too minor to elaborate on; it simply allows ONNX to automatically truncate overly long text, so no additional explanation is needed.

**Comment by wxywb** [comment]
> Update documentation or example to reflect this new feature?

Since it's a minor feature, it simply allows long text to be automatically truncated. Therefore, there doesn't seem to be a need to explicitly showcase this feature.

**Pull request merged**
